{"name": "Оформление заказа залогинниным пользователем", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_functional.TestFunctions object at 0x00000245CB7F13D0>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"0e3e1036-36d4-4bf5-a0d4-8b750d8b91b3\")>\ncreate_user = ({'email': 'matthew81@example.com', 'name': 'Daniel Hoover', 'password': '14CQmxnt^6'}, {'message': 'User already exists', 'success': False}, 403)\n\n    @allure.title('Оформление заказа залогинниным пользователем')\n    def test_order_login_user(self, driver, create_user):\n        func = FunctionsPage(driver)\n    \n        func.wait_button_constructor()\n        func.login_to_account(create_user)\n    \n>       func.wait_bun()\n\ntests\\test_functional.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\functional_page.py:55: in wait_bun\n    self.wait_clickable_element(FunctionalLocators.BUN)\npages\\base_page.py:16: in wait_clickable_element\n    return WebDriverWait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0e3e1036-36d4-4bf5-a0d4-8b750d8b91b3\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x00000245CBAA2C00>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Ожидание кнопки «Конструктор»", "status": "passed", "start": 1742085338772, "stop": 1742085338813}, {"name": "Вход в аккаунт", "status": "passed", "parameters": [{"name": "create_user", "value": "({'email': 'matthew81@example.com', 'password': '14CQmxnt^6', 'name': 'Daniel Hoover'}, {'success': False, 'message': 'User already exists'}, 403)"}], "start": 1742085338813, "stop": 1742085339429}, {"name": "Ожидание булочки", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\tereh\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\tereh\\Diplom_3\\pages\\functional_page.py\", line 55, in wait_bun\n    self.wait_clickable_element(FunctionalLocators.BUN)\n  File \"C:\\Users\\tereh\\Diplom_3\\pages\\base_page.py\", line 16, in wait_clickable_element\n    return WebDriverWait(self.driver, timeout).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\tereh\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1742085339429, "stop": 1742085349593}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1742085338772, "stop": 1742085349649, "uuid": "2f54db63-9f81-4ab0-a009-5ae224896f4a", "historyId": "e3786d9947b8120c8807dc8a5337b213", "testCaseId": "56a3bed2d0845eaa453c20edb535fe7b", "fullName": "tests.test_functional.TestFunctions#test_order_login_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_functional"}, {"name": "subSuite", "value": "TestFunctions"}, {"name": "host", "value": "TerekhovHONOR"}, {"name": "thread", "value": "18520-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_functional"}]}